

//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pain
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class Model1Container : DbContext
{
    public Model1Container()
        : base("name=Model1Container")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public DbSet<Person> PersonSet { get; set; }

    public DbSet<Visit> VisitSet { get; set; }

    public DbSet<Service> ServiceSet { get; set; }

    public DbSet<TypeOfRoom> TypeOfRoomSet { get; set; }

    public DbSet<Room> RoomSet { get; set; }

    public DbSet<Job> JobSet { get; set; }

    public DbSet<TypeOfService> TypeOfServiceSet { get; set; }

    public DbSet<TypeOfPrice> TypeOfPriceSet { get; set; }

}

}

