
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pain
{

using System;
    using System.Collections.Generic;
    
public partial class Service
{

    public Service()
    {

        this.Client = new HashSet<Client>();

    }


    public int Id { get; set; }

    public System.DateTime Date { get; set; }

    public int NumberOfPeople { get; set; }

    public int NumberOfHours { get; set; }

    public int VisitId { get; set; }

    public int ClientId { get; set; }



    public virtual ICollection<Client> Client { get; set; }

    public virtual TypeOfService TypeOfService { get; set; }

}

}
