
//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Pain
{

using System;
    using System.Collections.Generic;
    
public partial class TypeOfRoom
{

    public TypeOfRoom()
    {

        this.Room = new HashSet<Room>();

    }


    public int Id { get; set; }

    public string Type { get; set; }

    public int Capacity { get; set; }

    public int Price { get; set; }



    public virtual ICollection<Room> Room { get; set; }

}

}
